FXSitecore/AD.Alipay/Models/AlipaySubmitModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AD.Alipay.Models
{
    public class AlipaySubmitModel
    {
        public string HTML_Snippet { get; set; }
    }
}

FXSitecore/AD.Alipay/Models/AlipayViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AD.Alipay.Models
{
    public class AlipayViewModel
    {
    }
}

FXSitecore/AD.Alipay/Controllers/AlipayController.cs
using AD.Alipay.Models;
using Aop.Api;
using Aop.Api.Domain;
using Aop.Api.Request;
using Aop.Api.Response;
using Sitecore.Mvc.Controllers;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Text;
using System.Web.Mvc;

namespace AD.Alipay.Controllers
{
    public class AlipayController : SitecoreController
    {
        public ActionResult AlipayForm()
        {
            return View("~/Views/Alipay/AlipayForm.cshtml");
        }

        //[HttpPost]
        //public ActionResult AlipaySubmit(FormCollection formFields)
        //{
        //    List<string> values = new List<string>();

        //    foreach(var key in formFields.AllKeys)
        //    {
        //        values.Add(formFields[key]);
        //    }

        //    /////////////////////////////////////////////////

        //    var out_trade_no = formFields["out_trade_no"];
        //    var companyName = formFields["CompanyName"];
        //    var customerName = formFields["customerName"];
        //    var cutomerPhone = formFields["txtPhone"];
        //    var subject = formFields["hidproduct"];
        //    var fee = formFields["price"];

        //    double doubleFee;

        //    if(!double.TryParse(fee, out doubleFee))
        //    {
        //        return View("~/Views/Alipay/AlipayForm.cshtml");
        //    }



        //    if (string.IsNullOrEmpty(out_trade_no))
        //    {
        //        out_trade_no = DateTime.Now.ToString("yyyyMMddhhmmss");
        //    }

        //    string fullOutTradeNo = customerName + out_trade_no;


        //    string notifyUrl = Config.notify_url;

        //    switch (companyName)
        //    {
        //        case "FX_Industrial":
        //            notifyUrl = Config.notify_url;
        //            break;
        //        case "FX_Shanghai":
        //            notifyUrl = Config.notify_url;
        //            break;
        //        case "FX_Leasing":
        //            notifyUrl = Config.notify_url;
        //            break;
        //        default:
        //            notifyUrl = Config.notify_url;
        //            break;
        //    }

        //    //SortedDictionary<string, string> sParaTemp = new SortedDictionary<string, string>();
        //    //sParaTemp.Add("service", Config.service);
        //    //sParaTemp.Add("partner", Config.partner);
        //    //sParaTemp.Add("_input_charset", Config.input_charset.ToLower());
        //    //sParaTemp.Add("notify_url", notifyUrl);
        //    //sParaTemp.Add("return_url", Config.return_url);
        //    //sParaTemp.Add("out_trade_no", fullOutTradeNo);
        //    //sParaTemp.Add("subject", subject);
        //    ////sParaTemp.Add("rmb_fee", doubleFee.ToString());
        //    //sParaTemp.Add("rmb_fee", doubleFee.ToString());
        //    //sParaTemp.Add("product_code", "NEW_OVERSEAS_SELLER");
        //    //sParaTemp.Add("body", subject);
        //    //sParaTemp.Add("currency", "USD");


        //    SortedDictionary<string, string> sParaTemp = new SortedDictionary<string, string>();
        //    sParaTemp.Add("service", Config.service);
        //    sParaTemp.Add("partner", Config.partner);
        //    sParaTemp.Add("_input_charset", Config.input_charset.ToLower());
        //    sParaTemp.Add("notify_url", notifyUrl);
        //    sParaTemp.Add("return_url", Config.return_url);
        //    sParaTemp.Add("out_trade_no", fullOutTradeNo);
        //    sParaTemp.Add("subject", subject);
        //    //sParaTemp.Add("rmb_fee", doubleFee.ToString());
        //    sParaTemp.Add("total_fee", doubleFee.ToString());
        //    sParaTemp.Add("payment_type", "1");
        //    sParaTemp.Add("paymethod", "bankPay");
        //    sParaTemp.Add("seller_email", "alipay-fxid@chn.fujixerox.com");
        //    //sParaTemp.Add("Seller_id", Config.partner);
        //    //sParaTemp.Add("Seller_account_name", "alipay-fxid@chn.fujixerox.com");
        //    //sParaTemp.Add("product_code", "FAST_INSTANT_TRADE_PAY");


        //    string sHtmlText = Submit.BuildRequest(sParaTemp, "get", "确认");

        //    var viewModel = new AlipaySubmitModel();

        //    viewModel.HTML_Snippet = sHtmlText;

        //    return View("~/Views/Alipay/AlipaySubmit.cshtml", viewModel);
        //}

        [HttpPost]
        public ActionResult AlipaySubmit(FormCollection formFields)
        {

            DefaultAopClient client = new DefaultAopClient(Config.gatewayUrl, Config.app_id, Config.private_key, "json", "1.0", Config.sign_type, Config.alipay_public_key, Config.charset, true);

            var out_trade_no = formFields["out_trade_no"].Trim();
            var companyName = formFields["CompanyName"];
            var customerName = formFields["customerName"];
            var cutomerPhone = formFields["txtPhone"];
            var subject = formFields["hidproduct"];
            var fee = formFields["price"];

            double doubleFee;

            if (!double.TryParse(fee, out doubleFee))
            {
                return Redirect(Request.UrlReferrer.AbsoluteUri);
            }

            string total_amout = doubleFee.ToString();


            if (string.IsNullOrEmpty(out_trade_no))
            {
                out_trade_no = DateTime.Now.ToString("yyyyMMddhhmmss");
            }

            string fullOutTradeNo = customerName + out_trade_no;


            string notifyUrl = Config.notify_url1;

            switch (companyName)
            {
                case "FX_Industrial":
                    notifyUrl = Config.notify_url1;
                    break;
                case "FX_Shanghai":
                    notifyUrl = Config.notify_url2;
                    break;
                case "FX_Leasing":
                    notifyUrl = Config.notify_url3;
                    break;
                default:
                    notifyUrl = Config.notify_url1;
                    break;
            }


            // 组装业务参数model
            AlipayTradePagePayModel model = new AlipayTradePagePayModel();
            model.Subject = subject;
            model.TotalAmount = total_amout;
            model.OutTradeNo = fullOutTradeNo;
            model.ProductCode = "FAST_INSTANT_TRADE_PAY";

            AlipayTradePagePayRequest request = new AlipayTradePagePayRequest();
            // 设置同步回调地址
            request.SetReturnUrl(Config.return_url);
            // 设置异步通知接收地址
            request.SetNotifyUrl(notifyUrl);
            // 将业务model载入到request
            request.SetBizModel(model);

            AlipayTradePagePayResponse response = null;
            try
            {
                Diagnostics.AlipayLogger.Log.Info("SUBMISSION: " + model.Subject + "/" + model.TotalAmount + "/" + model.OutTradeNo);

                response = client.pageExecute(request, null, "post");

                var viewModel = new AlipaySubmitModel();
                viewModel.HTML_Snippet = response.Body;

                Diagnostics.AlipayLogger.Log.Info("RESPONSE: " + response.Body);

                return View("~/Views/Alipay/AlipaySubmit.cshtml", viewModel);
            }
            catch (Exception exp)
            {
                Diagnostics.AlipayLogger.Log.Error(exp.ToString());
                throw exp;
            }


        }


    }
}

FXSitecore/AD.Alipay/Views/Alipay/AlipayForm.cshtml
@using Sitecore.Mvc
@using System.Web.Mvc.Html

<div class="main-content">
    <div class="layout-main">
        <section class="section">
            <div class="alipay-form">
                <h1>支付宝</h1>
                @using (Html.BeginForm("AlipaySubmit", "Alipay", FormMethod.Post, new { id="form1" }))
                {
                    <table width="890px" cellspacing="0" cellpadding="0" border="0" align="center">
                        <tbody>
                            <tr>
                                <td class="left-column"><span class="required">*</span>公司名称：</td>
                                <td>
                                    <p>
                                        <input class="has-outline" id="CompanyName1" type="radio" name="CompanyName" value="FX_Industrial" checked>
                                        <label for="CompanyName1">富士施乐实业发展（中国）有限公司</label><a href="https://www1.fujixerox.com.cn/pay/helpfiles/fxid_how_get.htm" target="_blank" style="padding-left:30px;">如何获取订单\合同号、发票号</a><br>			              （alipay-fxid@chn.fujixerox.com）<br>
                                    </p>
                                    <p>
                                        <input class="has-outline" id="CompanyName2" type="radio" name="CompanyName" value="FX_Shanghai">
                                        <label for="CompanyName2">富士施乐（中国）有限公司上海分公司</label><a href="https://www1.fujixerox.com.cn/pay/helpfiles/fxcl_sh_how_get.htm" target="_blank" style="padding-left:15px;">如何获取订单\合同号、发票号</a><br>			              （alipay-fxcl@chn.fujixerox.com）<br>
                                    </p>
                                    <p>
                                        <input class="has-outline" id="CompanyName3" type="radio" name="CompanyName" value="FX_Leasing">
                                        <label for="CompanyName3">富士施乐租赁（中国）有限公司</label><a href="https://www1.fujixerox.com.cn/pay/helpfiles/fxlcl_how_get.htm" target="_blank" style="padding-left:57px;">如何获取订单\合同号、发票号</a><br>			              （alipay-fxlcl@chn.fujixerox.com）<br>
                                    </p>
                                </td>
                            </tr>
                            <tr>
                                <td class="left-column">
                                    <label class="required" for="price">*<span> 付总价：</span></label>
                                </td>
                                <td>
                                    <input class="has-outline" id="price" style="width:400px;" name="price" hint="应付总价" allownull="false" size="36" ><span class="help-text">金额格式例如: 52.2或3</span>
                                </td>
                            </tr>
                            <tr>
                                <td class="left-column" rowspan="2">
                                    <label class="required" for="product1">*<span> 富士施乐订单\合同号、发票号：</span></label>
                                </td>
                                <td>
                                    <input class="has-outline" id="product1" style="width:400px;" name="product1" hint="富士施乐订单合同号、发票号" allownull="false" size="36" ><br>
                                    <input class="has-outline" id="raproduct1_2" type="radio" name="raproduct1" value="Invoice No." checked>
                                    <label for="raproduct1_2">发票号</label>
                                    <input class="has-outline" id="raproduct1_1" type="radio" name="raproduct1" value="PO No.">
                                    <label for="raproduct1_1">订单\合同号</label>
                                    <div id="newInvoice"></div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <button class="addNewInvoice" type="button">增加</button>
                                </td>
                            </tr>
                            <tr>
                                <td class="left-column">
                                    <label class="required" for="customerName">*<span> 客户姓名：</span></label>
                                </td>
                                <td>
                                    <input class="has-outline" id="customerName" style="width:400px;" name="customername" hint="客户姓名" allownull="false" size="36" >
                                </td>
                            </tr>
                            <tr>
                                <td class="left-column">
                                    <label class="required" for="txtPhone">*<span> 客户联系电话：</span></label>
                                </td>
                                <td>
                                    <input class="has-outline" id="txtPhone" style="width:400px;" name="customertel" hint="客户联系电话" allownull="false" size="36" ><span class="help-text">格式为：057126880000</span>
                                </td>
                            </tr>
                            <tr>
                                <td class="left-column">
                                    <label class="required" for="customercompany">*<span> 客户公司名称：</span></label>
                                </td>
                                <td>
                                    <input class="has-outline" id="customercompany" style="width:400px;" name="customercompany" hint="客户公司名称" allownull="false" size="36" >
                                </td>
                            </tr>
                            <tr>
                                <td> </td>
                                <td>
                                    <button class="submitForm" type="submit">支付宝支付</button>
                                    <button class="reset" type="button">重置</button>
                                </td>
                            </tr>
                            <tr>
                                <td class="font14" height="3" colspan="2">
                                    <div class="payment">
                                        <h3>目前支持四种付款方式：</h3><strong>支付宝余额付款：</strong> 当支付宝账户中有余额时，直接输入支付密码即可完成付款，支持大额商品购买，可以先多次充值再付款。<br><strong>网上银行付款：</strong> 只要您拥有一张支付宝合作银行的银行卡，并开通了网上支付功能，即可顺利支付。支付时无需填写支付宝账户，且如果您尚未注册支付宝账户，将免费获得账户。<a target="_blank" href="http://abc.alipay.com">了解详情</a><br><strong>"支付宝卡通"付款：</strong> 开通"支付宝卡通"就可直接进行网上付款，不再需要开通网上银行。<br><strong>网点付款：</strong> 只需到与支付宝合作的营业网点，用现金或刷卡即可完成网上订单付款和支付宝账户充值。
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <input id="hidCountInvoice" type="hidden" name="hidCountInvoice" value="1">
                    <input id="hidproduct" type="hidden" name="hidproduct">
                    <input id="hidbody" type="hidden" name="hidbody">
                    <input id="out_trade_no" type="hidden" name="out_trade_no">
                }
                <script>

                    var out_trade_no = document.getElementById("out_trade_no");
                    //Set the time formating function
                    Date.prototype.format = function (format) {
                        var args = {
                            "M+": this.getMonth() + 1,
                            "d+": this.getDate(),
                            "h+": this.getHours(),
                            "m+": this.getMinutes(),
                            "s+": this.getSeconds(),
                        };
                        if (/(y+)/.test(format))
                            format = format.replace(RegExp.$1, (this.getFullYear() + "").substr(4 - RegExp.$1.length));
                        for (var i in args) {
                            var n = args[i];
                            if (new RegExp("(" + i + ")").test(format))
                                format = format.replace(RegExp.$1, RegExp.$1.length == 1 ? n : ("00" + n).substr(("" + n).length));
                        }
                        return format;
                    };

                    out_trade_no.value = new Date().format("yyyyMMddhhmmss");

                </script>

            </div>
        </section>
    </div>
</div>

FXSitecore/AD.Alipay/Views/Alipay/AlipaySubmit.cshtml
@using Sitecore.Mvc
@using System.Web.Mvc.Html
@model AD.Alipay.Models.AlipaySubmitModel

<div class="main-content" style='position: absolute !important; top: -9999px !important;left: -9999px !important;'>
    <div class="layout-main">
        <section class="section">
            <div class="alipay-form">
                @Html.Raw(Model.HTML_Snippet)
            </div>
        </section>
    </div>
</div>